name: Build Hugo website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 🚚 Checkout

      - uses: actions/setup-node@v3
        name: 🔧 Setup Node
        with:
          node-version: '18'

      - name: 🔧 Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: 📅 Download speakers and sessions from Sessionize
        run: |
          curl https://sessionize.com/api/v2/wc4as1wz/view/All -s -o ./data/sessionize.json
          cp ./data/sessionize.json ./data/Y2024/sessionize.json
          
      - name: 📆 Generate ICS files
        run: node utils/generate-ics.js

      - name: 👩‍🏭 Build
        run: hugo --minify

      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: globalazure.at
